export {
    getGridByID,
    OWPTGAddRow,
    OWPTGCopyRow,
    OWPTGDataList,
    OWPTGDelete,
    OWPTGDelEvent,
    OWPTGExport,
    OWPTGExportExcel,
    OWPTGExportExcelToSubject,
    OWPTGExportExcelToSubjectByPageNo,
    OWPTGExportPDF,
    OWPTGSave,
    OWPTGSaveMulti,
    OWPTGSelect,
    OWPTGUpdateRow,
} from './TGEvent';
